In [9]:
# --- Google Colab Setup (Cell 0) ---
# This cell installs Ollama, starts the server, and pulls the specific model.

print("Installing necessary Python packages...")
# Remove pandas/numpy/matplotlib/requests/scikit-learn from !pip as they are usually pre-installed
# Adding explicitly to ensure if not present (though they generally are)
!pip install pandas numpy scikit-learn requests

print("Installing Ollama...")
# Download and execute the Ollama installation script
!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time
import os
import socket
from pathlib import Path

# Set environment variable for Ollama to listen on all interfaces within the Colab VM
# This allows other Colab cells to connect to the Ollama server.
os.environ['OLLAMA_HOST'] = '0.0.0.0'
OLLAMA_PORT = 11434 # Ollama's default API port

print("Ensuring no previous Ollama processes are running...")
# Kill any existing Ollama processes to ensure a clean start
!pkill ollama || true

print(f"Starting Ollama server on port {OLLAMA_PORT} in background...")
# Start the Ollama server as a background process
ollama_process = subprocess.Popen(["ollama", "serve"],
                                  stdout=subprocess.DEVNULL, # Redirect stdout to /dev/null
                                  stderr=subprocess.DEVNULL, # Redirect stderr to /dev/null
                                  preexec_fn=os.setsid) # Detach from the current process group
print(f"Ollama server process started with PID: {ollama_process.pid}")

print(f"Waiting for Ollama server to become available on port {OLLAMA_PORT}...")
max_wait_time = 90 # seconds (increased for model loading)
start_time = time.time()
server_ready = False

# Loop to check if the Ollama server is responsive
while time.time() - start_time < max_wait_time:
    try:
        # Attempt to create a socket connection to the Ollama server
        with socket.create_connection(('127.0.0.1', OLLAMA_PORT), timeout=1):
            server_ready = True
            break
    except (ConnectionRefusedError, socket.timeout):
        # If connection is refused or times out, check if the Ollama process is still running
        if ollama_process.poll() is not None:
            print(f"Ollama server process died unexpectedly (exit code: {ollama_process.poll()}).")
            print("Please check previous logs for errors or try restarting the runtime.")
            server_ready = False
            break
        print(f"  Still waiting for Ollama... ({int(time.time() - start_time)}s elapsed)")
        time.sleep(5) # Wait 5 seconds before retrying
    except Exception as e:
        print(f"An unexpected error occurred during Ollama startup check: {e}")
        server_ready = False
        break

if not server_ready:
    print(f"Ollama server did not become available on port {OLLAMA_PORT} within {max_wait_time} seconds. Aborting setup.")
    if ollama_process.poll() is None: # If the process is still running, try to terminate it
        ollama_process.terminate()
        print("Attempted to terminate non-responsive Ollama process.")
    raise RuntimeError("Ollama server failed to start or become ready.")
else:
    print(f"Ollama server is now available on port {OLLAMA_PORT}.")

# --- Pull the specific model for this notebook ---
MODEL_NAME = "gemma:2b-instruct-q4_0" # <--- MODEL TO PULL FOR THIS NOTEBOOK
print(f"\nPulling {MODEL_NAME} model...")
# Run the ollama pull command
pull_process = subprocess.run(["ollama", "pull", MODEL_NAME], capture_output=True, text=True)
print(pull_process.stdout)
if pull_process.stderr:
    print("Ollama pull stderr:", pull_process.stderr)
    if "Error" in pull_process.stderr or "failed" in pull_process.stderr.lower():
        raise RuntimeError(f"Failed to pull Ollama model: {pull_process.stderr}")
print(f"{MODEL_NAME} pull complete.")

# Check if model is available (list all downloaded models)
list_process = subprocess.run(["ollama", "list"], capture_output=True, text=True)
print(f"\nAvailable Ollama models after pulling {MODEL_NAME}:")
print(list_process.stdout)
if list_process.stderr:
    print("Ollama list stderr:", list_process.stderr)

# Verify GPU availability with nvidia-smi
print("\nChecking GPU availability with nvidia-smi...")
!nvidia-smi

# Set the base URL and model name as environment variables for use in subsequent cells
OLLAMA_API_BASE_URL = f"http://127.0.0.1:{OLLAMA_PORT}"
print(f"Set Ollama API base URL for direct requests to: {OLLAMA_API_BASE_URL}")
%env OLLAMA_MODEL_NAME=$MODEL_NAME
%env OLLAMA_API_BASE_URL=$OLLAMA_API_BASE_URL

Installing necessary Python packages...
Installing Ollama...
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
Ensuring no previous Ollama processes are running...
Starting Ollama server on port 11434 in background...
Ollama server process started with PID: 8078
Waiting for Ollama server to become available on port 11434...
  Still waiting for Ollama... (0s elapsed)
Ollama server is now available on port 11434.

Pulling gemma:2b-instruct-q4_0 model...

Ollama pull stderr: pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest 
pulling c1864a5eb193: 100% ▕██████████

In [10]:
# Cell 1: Initialize Client & Confirm Server is Running
import os
import json
import pandas as pd
import numpy as np # Used later for classification_report
import matplotlib.pyplot as plt # Used later for plotting
import requests
import time
import socket
import re

# Use the API base URL from the environment variable set in Cell 0
base_url = os.getenv('OLLAMA_API_BASE_URL')
api_url_generate = f"{base_url}/api/generate" # Direct generate endpoint
api_url_show = f"{base_url}/api/show" # To check model details

print(f"Using Ollama API at: {base_url}")
print(f"Model to use: {os.getenv('OLLAMA_MODEL_NAME')}")


# Confirm server is running and model is accessible (more robust check)
def check_ollama_and_model(base_url, model_name):
    try:
        # Check if Ollama server is generally responsive
        response = requests.get(f"{base_url}/api/tags", timeout=10)
        response.raise_for_status() # Raise an exception for bad status codes
        print("Ollama server is responsive.")

        # Check if the specific model is loaded
        payload = {"name": model_name}
        response = requests.post(api_url_show, json=payload, timeout=10)
        response.raise_for_status()
        print(f"Model '{model_name}' is loaded and accessible.")
        return True
    except requests.exceptions.ConnectionError as e:
        print(f"Error: Could not connect to Ollama server at {base_url}. Please ensure it's running.")
        print(f"Details: {e}")
        return False
    except requests.exceptions.Timeout:
        print(f"Error: Request to Ollama server timed out.")
        return False
    except requests.exceptions.RequestException as e:
        print(f"Error checking Ollama or model: {e}")
        if response:
            print(f"Response status: {response.status_code}")
            print(f"Response body: {response.text}")
        return False

if not check_ollama_and_model(base_url, os.getenv('OLLAMA_MODEL_NAME')):
    raise RuntimeError("Ollama server or model not ready. Please check Cell 0 execution.")
else:
    print("Ollama server and model are ready for use.")

# Note: The OpenAI client (from `openai` library) is not directly used here
# because we're interacting with Ollama's native API via `requests` as set up.
# If you explicitly need `openai` client for `ollama` (e.g., using `ollama run --port 8000`),
# then ensure `base_url` points to that port and the `client` object is initialized.

Using Ollama API at: http://127.0.0.1:11434
Model to use: gemma:2b-instruct-q4_0
Ollama server is responsive.
Model 'gemma:2b-instruct-q4_0' is loaded and accessible.
Ollama server and model are ready for use.


In [11]:
# Cell 2: Load Full Prepared Dataset (2400 Samples) and create stratified splits
import pandas as pd
from sklearn.model_selection import train_test_split # We can use this or manual group by

# Load the already-prepared dataset. Adjust path if your file is in Google Drive.
full_df = pd.read_csv('/content/cwe_top5_sampled_with_juliet_none.csv')
total_samples = len(full_df)
print(f"Total samples in full dataset: {total_samples}")

# Validate dataset
print("Validating full dataset...")
expected_cwes = {'CWE121', 'CWE78', 'CWE122', 'CWE190', 'CWE191', 'none'}
assert set(full_df['cwe'].unique()) == expected_cwes, "Unexpected CWE values found!"
assert full_df['code'].notna().all(), "Missing code values found!"

print("\nFull dataset CWE distribution:")
print(full_df['cwe'].value_counts())

# --- Create Stratified Training and Testing Splits ---
# We need 320 samples per class for training (1920 total)
# and 80 samples per class for testing (480 total).

train_split_df = pd.DataFrame()
test_split_df = pd.DataFrame()

# Group by 'cwe' and split each group
for cwe_type in expected_cwes:
    cwe_subset = full_df[full_df['cwe'] == cwe_type].reset_index(drop=True)

    # Ensure there are enough samples for the split
    if len(cwe_subset) < (320 + 80):
        print(f"Warning: Not enough samples for CWE type '{cwe_type}'. Expected at least 400, found {len(cwe_subset)}. This might cause issues.")
        # Handle cases where there might not be 400 samples per class if necessary
        # For now, we'll proceed, but it might result in fewer than 320/80 if data is short.

    # Take the first 320 for training, and next 80 for testing for each CWE type
    train_split_df = pd.concat([train_split_df, cwe_subset.iloc[:320]])
    test_split_df = pd.concat([test_split_df, cwe_subset.iloc[320:320+80]]) # Ensure it's 320+80 if some subsets are smaller

# Shuffle the splits to randomize the order within them, important for training/batching
train_split_df = train_split_df.sample(frac=1, random_state=42).reset_index(drop=True)
test_split_df = test_split_df.sample(frac=1, random_state=42).reset_index(drop=True)


print(f"\nTraining split size: {len(train_split_df)} samples")
print("Training split CWE distribution:")
print(train_split_df['cwe'].value_counts())

print(f"\nTesting split size: {len(test_split_df)} samples")
print("Testing split CWE distribution:")
print(test_split_df['cwe'].value_counts())

print("\nSample code from training split:", train_split_df['code'].iloc[0][:100]) # Truncate for display
print("Sample code from testing split:", test_split_df['code'].iloc[0][:100])

# Display head of splits (optional)
print("\nTrain Split Head:")
print(train_split_df.head())
print("\nTest Split Head:")
print(test_split_df.head())

Total samples in full dataset: 2400
Validating full dataset...

Full dataset CWE distribution:
cwe
CWE121    400
CWE78     400
CWE190    400
CWE191    400
CWE122    400
none      400
Name: count, dtype: int64

Training split size: 1920 samples
Training split CWE distribution:
cwe
CWE122    320
none      320
CWE191    320
CWE121    320
CWE190    320
CWE78     320
Name: count, dtype: int64

Testing split size: 480 samples
Testing split CWE distribution:
cwe
CWE190    80
none      80
CWE121    80
CWE122    80
CWE78     80
CWE191    80
Name: count, dtype: int64

Sample code from training split: #include "std_testcase.h"
#ifdef _WIN32
#include <winsock2.h>
#include <windows.h>
#include <direct.
Sample code from testing split: #include "std_testcase.h"
unsigned int var;
unsigned int var;
unsigned int var;
#ifndef OMITBAD
void

Train Split Head:
                                                file     cwe label  \
0  CWE122_Heap_Based_Buffer_Overflow__c_CWE129_co...  CWE122  good   
1        

In [12]:
# Cell 3: Define Prompt (Exact from Old Code)
# The prompt is critical for guiding the model's output to your desired JSON format.
prompt = (
    "You are a security analysis tool. Analyze the C source code for vulnerabilities and respond **only** with a JSON object containing 'reason' and 'answer' fields. Do not include any additional text, explanations, or markdown outside the JSON. Use this exact format:\n"
    "{ \"reason\": \"Explanation of vulnerability\", \"answer\": \"CWE121\" }\n"
    "The 'answer' field must be one of: 'CWE121', 'CWE78', 'CWE122', 'CWE190', 'CWE191', or 'none'. Match the 'answer' to the vulnerability type described in the 'reason'. Examples:\n"
    "- Code with `memcpy` without bounds check: { \"reason\": \"Stack-based buffer overflow due to unchecked memcpy\", \"answer\": \"CWE121\" }\n"
    "- Code with `system` using user input: { \"reason\": \"OS command injection via unsanitized input to system\", \"answer\": \"CWE78\" }\n"
    "- Code with `malloc` and overflow: { \"reason\": \"Heap-based buffer overflow due to improper malloc usage\", \"answer\": \"CWE122\" }\n"
    "- Code with large integer multiplication: { \"reason\": \"Integer overflow from unchecked multiplication\", \"answer\": \"CWE190\" }\n"
    "- Code with negative integer decrement: { \"reason\": \"Integer underflow from unchecked decrement\", \"answer\": \"CWE191\" }\n"
    "- Code with no obvious vulnerability: { \"reason\": \"No vulnerability detected\", \"answer\": \"none\" }\n"
    "Here is the code:\n\n"
)

# Apply the prompt to both training and testing splits
train_split_df['full_prompt'] = prompt + "\n\n" + train_split_df['code']
test_split_df['full_prompt'] = prompt + "\n\n" + test_split_df['code']

print("Prompt sample from training split (truncated):", train_split_df['full_prompt'].iloc[0][:500])
print("\nPrompt sample from testing split (truncated):", test_split_df['full_prompt'].iloc[0][:500])

Prompt sample from training split (truncated): You are a security analysis tool. Analyze the C source code for vulnerabilities and respond **only** with a JSON object containing 'reason' and 'answer' fields. Do not include any additional text, explanations, or markdown outside the JSON. Use this exact format:
{ "reason": "Explanation of vulnerability", "answer": "CWE121" }
The 'answer' field must be one of: 'CWE121', 'CWE78', 'CWE122', 'CWE190', 'CWE191', or 'none'. Match the 'answer' to the vulnerability type described in the 'reason'. Exam

Prompt sample from testing split (truncated): You are a security analysis tool. Analyze the C source code for vulnerabilities and respond **only** with a JSON object containing 'reason' and 'answer' fields. Do not include any additional text, explanations, or markdown outside the JSON. Use this exact format:
{ "reason": "Explanation of vulnerability", "answer": "CWE121" }
The 'answer' field must be one of: 'CWE121', 'CWE78', 'CWE122', 'CWE190', 'C

In [13]:
# Cell 4: Create Backups directory and initialize response lists
from pathlib import Path
import json
import pandas as pd # Ensure pandas is imported

# Define paths for Colab environment
BACKUP_DIR = Path("/content/CodeSentinel/Backups")
RESULTS_DIR = Path("/content/CodeSentinel/Results/_2")

BACKUP_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Define backup filenames for each split
MODEL_NAME = os.getenv('OLLAMA_MODEL_NAME').replace(':', '_').replace('/', '-') # Sanitize model name for filename
TRAIN_BACKUP_PATH = BACKUP_DIR / f"Result-{MODEL_NAME}-CWE-train.csv"
TEST_BACKUP_PATH = BACKUP_DIR / f"Result-{MODEL_NAME}-CWE-test.csv"

def save_responses(responses_list, path):
    """Saves a list of raw string responses to a CSV file."""
    print(f"Debug: Responses before saving to {path}:")
    cleaned_responses = []
    for idx, response in enumerate(responses_list):
        if pd.isna(response) or response is None:
            print(f"Response {idx} is invalid (NaN/None), replacing with fallback for saving.")
            response = json.dumps({"reason": "Invalid response", "answer": "none"})
        # Ensure it's a string representation of JSON
        if not isinstance(response, str):
            response = json.dumps(response) # Convert dicts back to string JSON if needed
        print(f"Response {idx}: {response[:100]}... (type: {type(response)})") # Truncate for print
        cleaned_responses.append(response)
    df = pd.DataFrame(cleaned_responses, columns=['raw_response_json_string'])
    df.to_csv(path, index=False)
    print(f"Responses saved to: {path}")

# Start fresh by resetting responses for both splits
training_responses = []
testing_responses = []
print("Response lists reset to empty for fresh start.")

Response lists reset to empty for fresh start.


In [14]:
# Cell 5: Run Inference Loops for Training and Testing Splits
import requests
import time
import json
import os # Make sure os is imported
from tqdm.notebook import tqdm # For nice progress bars in Colab
from sklearn.metrics import confusion_matrix, classification_report # For evaluation later

# Retrieve API details from environment variables
api_url_generate = f"{os.getenv('OLLAMA_API_BASE_URL')}/api/generate"
MODEL_NAME_FULL = os.getenv('OLLAMA_MODEL_NAME') # The full model name with colon

max_retries = 3
retry_delay = 5  # seconds
debug_mode = False # Set to True for very verbose logging per request (can slow down)

def process_dataframe_for_inference(df_to_process, response_list_target):
    """
    Processes a DataFrame, sends prompts to Ollama, and appends raw responses to a list.
    Handles retries and errors.
    """
    err_logs_local = []
    print(f"\nStarting inference for {len(df_to_process)} samples using model '{MODEL_NAME_FULL}'...")

    for index, row in tqdm(df_to_process.iterrows(), total=len(df_to_process), desc="Processing Samples"):
        attempts = 0
        success = False
        source_code = row['code'] # Use original code from row for prompt construction
        full_prompt_text = row['full_prompt'] # Use the pre-constructed full_prompt

        if debug_mode:
            print(f"\nASKED (Index {index}):")
            print(f"Source (truncated): {source_code[:200]}...")
            print(f"Full Prompt (truncated): {full_prompt_text[:300]}...")

        while attempts < max_retries and not success:
            try:
                if debug_mode:
                    print(f"Attempt {attempts + 1}: Sending request to {api_url_generate}...")
                start_time = time.time()
                payload = {
                    "model": MODEL_NAME_FULL,
                    "prompt": full_prompt_text,
                    "stream": False # We want the full response at once
                }

                if debug_mode:
                    print(f"Payload length: {len(payload['prompt'])} chars")

                response = requests.post(api_url_generate, json=payload, timeout=300) # Increased timeout to 300s (5 min) for large models/prompts
                response.raise_for_status() # Raise an error for bad status codes (4xx or 5xx)

                end_time = time.time()
                full_ollama_response = response.json()
                raw_content = full_ollama_response.get('response', '') # The actual text response from Ollama

                if debug_mode:
                    print(f"Request took {end_time - start_time:.2f} seconds")
                    print(f"Full Ollama JSON response: {json.dumps(full_ollama_response, indent=2)}")
                    print(f"Raw content from 'response' field: {raw_content[:200]}...")

                # Append the raw response string (or full JSON dict if preferred for later parsing)
                # Storing the full JSON dict ensures all metadata is preserved
                response_list_target.append(full_ollama_response)
                success = True

            except requests.RequestException as e:
                attempts += 1
                end_time = time.time()
                log_entry = {
                    "index": index,
                    "error_type": type(e).__name__,
                    "message": str(e),
                    "attempt": attempts,
                    "elapsed_time": end_time - start_time,
                    "response_status_code": getattr(response, 'status_code', 'N/A'),
                    "response_text_preview": getattr(response, 'text', 'No response')[:500]
                }
                err_logs_local.append(log_entry)
                print(f"ERROR at index {index}, attempt {attempts}/{max_retries} : {e}")
                print(f"Request failed after {end_time - start_time:.2f} seconds.")

                if attempts < max_retries:
                    print(f"Retrying in {retry_delay} seconds...")
                    time.sleep(retry_delay)
                else:
                    fallback_response_dict = {
                        "response": json.dumps({"reason": "Failed after max attempts", "answer": "none"}),
                        "status": "error",
                        "error_message": f"Max retries reached: {log_entry['message']}"
                    }
                    response_list_target.append(fallback_response_dict)
                    print(f"Max retries reached for index {index}, stored fallback response.")
            except Exception as e: # Catch any other unexpected errors
                attempts += 1
                end_time = time.time()
                log_entry = {
                    "index": index,
                    "error_type": type(e).__name__,
                    "message": str(e),
                    "attempt": attempts,
                    "elapsed_time": end_time - start_time,
                    "response_status_code": 'N/A', # No response object here
                    "response_text_preview": 'No response due to non-request error'
                }
                err_logs_local.append(log_entry)
                print(f"UNEXPECTED ERROR at index {index}, attempt {attempts}/{max_retries} : {e}")
                if attempts < max_retries:
                    print(f"Retrying in {retry_delay} seconds...")
                    time.sleep(retry_delay)
                else:
                    fallback_response_dict = {
                        "response": json.dumps({"reason": "Failed due to unexpected error", "answer": "none"}),
                        "status": "error",
                        "error_message": f"Unexpected error after max retries: {log_entry['message']}"
                    }
                    response_list_target.append(fallback_response_dict)
                    print(f"Max retries reached for index {index} due to unexpected error, stored fallback.")

    print(f"Inference loop finished. Total errors logged for this run: {len(err_logs_local)}")
    return err_logs_local

# Global error log list
all_err_logs = []

# --- Run inference for Training Split ---
print("--- Running Inference for Training Split ---")
train_err_logs = process_dataframe_for_inference(train_split_df, training_responses)
all_err_logs.extend(train_err_logs)
save_responses(training_responses, TRAIN_BACKUP_PATH)

# --- Run inference for Testing Split ---
print("\n--- Running Inference for Testing Split ---")
test_err_logs = process_dataframe_for_inference(test_split_df, testing_responses)
all_err_logs.extend(test_err_logs)
save_responses(testing_responses, TEST_BACKUP_PATH)

print("\nAll inference tasks complete.")

--- Running Inference for Training Split ---

Starting inference for 1920 samples using model 'gemma:2b-instruct-q4_0'...


Processing Samples:   0%|          | 0/1920 [00:00<?, ?it/s]

Inference loop finished. Total errors logged for this run: 0
Debug: Responses before saving to /content/CodeSentinel/Backups/Result-gemma_2b-instruct-q4_0-CWE-train.csv:
Response 0: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:42.805596966Z", "response": "{\n... (type: <class 'str'>)
Response 1: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:43.239350765Z", "response": "{ \... (type: <class 'str'>)
Response 2: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:43.935418718Z", "response": "{\n... (type: <class 'str'>)
Response 3: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:44.398160925Z", "response": "{ \... (type: <class 'str'>)
Response 4: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:45.051277486Z", "response": "{\n... (type: <class 'str'>)
Response 5: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:16:45.685937416Z", "response": "{ \... (type: <class 'str'>)
Re

Processing Samples:   0%|          | 0/480 [00:00<?, ?it/s]

Inference loop finished. Total errors logged for this run: 0
Debug: Responses before saving to /content/CodeSentinel/Backups/Result-gemma_2b-instruct-q4_0-CWE-test.csv:
Response 0: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:44.116120118Z", "response": "{ \... (type: <class 'str'>)
Response 1: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:44.54929832Z", "response": "{ \"... (type: <class 'str'>)
Response 2: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:44.991029818Z", "response": "{\n... (type: <class 'str'>)
Response 3: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:45.374652001Z", "response": "{ \... (type: <class 'str'>)
Response 4: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:45.813399394Z", "response": "{ \... (type: <class 'str'>)
Response 5: {"model": "gemma:2b-instruct-q4_0", "created_at": "2025-06-12T10:33:46.667566907Z", "response": "{\n... (type: <class 'str'>)
Res

In [2]:
# Cell 6: Parse and Evaluate Results (Fixed Multi-Class for Both Splits)
import re
import json
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np # For formatting confusion matrix

# Function to extract JSON from Ollama's full response object
def extract_json_from_ollama_response(ollama_response_dict):
    """
    Extracts the JSON object from Ollama's 'response' field, handling potential malformed JSON.
    Expected input: a dictionary from response.json()
    Expected output: a dictionary {"reason": ..., "answer": ...} or a fallback.
    """
    raw_response_text = ollama_response_dict.get('response', '')
    if not raw_response_text:
        return {"reason": "Empty or missing 'response' field from Ollama", "answer": "none"}

    try:
        # Find the first and last curly braces to extract the JSON string
        start = raw_response_text.find('{')
        end = raw_response_text.rfind('}') + 1

        if start != -1 and end != -1 and start < end:
            json_string = raw_response_text[start:end]
            return json.loads(json_string)
        else:
            return {"reason": f"No valid JSON found in response: '{raw_response_text}'", "answer": "none"}
    except json.JSONDecodeError as e:
        # Attempt to fix common JSON issues (e.g., single quotes)
        fixed_text = raw_response_text.replace("'", '"')
        try:
            return json.loads(fixed_text)
        except json.JSONDecodeError:
            return {"reason": f"Failed to parse JSON: {e} | Raw: '{raw_response_text}'", "answer": "none"}
    except Exception as e:
        return {"reason": f"Unexpected error during JSON extraction: {e} | Raw: '{raw_response_text}'", "answer": "none"}

def evaluate_results(df_original, responses_list, data_split_name):
    """
    Processes responses, calculates metrics, and prints evaluation report for a given data split.
    """
    print(f"\n--- Evaluating Results for {data_split_name} Split ({len(responses_list)} samples) ---")

    if not responses_list:
        print(f"No responses to evaluate for {data_split_name} split.")
        return

    # Create a DataFrame for model answers
    # Convert each item in responses_list (which are full Ollama response dicts) to the extracted JSON
    model_answers_dicts = [extract_json_from_ollama_response(res_dict) for res_dict in responses_list]
    model_answers_df = pd.DataFrame(model_answers_dicts)

    # Ensure model_answer and model_reason columns exist, providing defaults
    model_answers_df['model_answer'] = model_answers_df['answer'].fillna('none')
    model_answers_df['model_reason'] = model_answers_df['reason'].fillna('No reason provided')

    # Join with the original DataFrame subset to get true labels and other info
    # Ensure indices align correctly.
    # If the df_original was reset_index, then .iloc will correctly correspond.
    combined_df = df_original.reset_index(drop=True).copy()
    combined_df['model_answer'] = model_answers_df['model_answer']
    combined_df['model_reason'] = model_answers_df['model_reason']

    # Compute verdict
    combined_df['verdict'] = combined_df['cwe'] == combined_df['model_answer']

    # Compute multi-class metrics
    true_labels = combined_df['cwe']
    pred_labels = combined_df['model_answer']

    # Define all possible labels explicitly for consistent report and matrix
    all_labels = sorted(list(set(true_labels.unique()).union(set(pred_labels.unique()))))
    # If using specific set of labels for report consistency:
    # all_labels = ['CWE121', 'CWE78', 'CWE122', 'CWE190', 'CWE191', 'none']


    # AUC (Accuracy for multi-class, or one-vs-rest AUC if binary focus)
    # For multi-class classification, overall accuracy is often used.
    accuracy = combined_df['verdict'].mean()
    print(f"Accuracy ({data_split_name}): {accuracy:.3f}")


    # Confusion Matrix
    cm = confusion_matrix(true_labels, pred_labels, labels=all_labels)
    print(f"\nConfusion Matrix ({data_split_name}):")
    print("Labels order:", all_labels)
    print(cm)
    # For better display, you can use pd.DataFrame(cm, index=all_labels, columns=all_labels)


    # Classification Report
    report = classification_report(true_labels, pred_labels, labels=all_labels, zero_division=0)
    print(f"\nClassification Report ({data_split_name}):")
    print(report)

    # Save filtered results
    output_filename_base = f"Result-{MODEL_NAME}-{data_split_name}-CWE.csv"
    output_path = RESULTS_DIR / output_filename_base
    filtered_df_output = combined_df[['cwe', 'model_answer', 'verdict', 'model_reason', 'file', 'code']]
    filtered_df_output.to_csv(output_path, index=False)
    print(f"Filtered results saved to '{output_path}'")

# --- Perform evaluation for each split ---
evaluate_results(train_split_df, training_responses, "Training")
evaluate_results(test_split_df, testing_responses, "Testing")


if all_err_logs:
    print("\n--- Consolidated Error Log ---")
    for log_entry in all_err_logs:
        print(f"Index: {log_entry['index']}, Error Type: {log_entry['error_type']}, Message: {log_entry['message']}")
        if log_entry.get('response_status_code') != 'N/A':
            print(f"  Status: {log_entry['response_status_code']}, Preview: {log_entry['response_text_preview']}")
else:
    print("\nNo errors logged during inference.")

NameError: name 'train_split_df' is not defined

## --- Evaluating Results for Training Split (1920 samples) ---
Accuracy (Training): **0.426**

### Confusion Matrix (Training):
Labels order: ['CWE121', 'CWE122', 'CWE190', 'CWE191', 'CWE78', 'none']
```text
[[162 131   9   1   5  12]
 [123 165   7   1   6  18]
 [149  49  71   3  24  24]
 [128  30  94  17  17  34]
 [ 40  28  55   0 176  21]
 [ 83   0   9   2   0 226]]
```

### Classification Report (Training):
```text
              precision    recall  f1-score   support

      CWE121       0.24      0.51      0.32       320
      CWE122       0.41      0.52      0.46       320
      CWE190       0.29      0.22      0.25       320
      CWE191       0.71      0.05      0.10       320
       CWE78       0.77      0.55      0.64       320
        none       0.67      0.71      0.69       320

    accuracy                           0.43      1920
   macro avg       0.52      0.43      0.41      1920
weighted avg       0.52      0.43      0.41      1920
```
## --- Evaluating Results for Testing Split (480 samples) ---
Accuracy (Testing): **0.412**

### Confusion Matrix (Testing):
Labels order: ['CWE121', 'CWE122', 'CWE190', 'CWE191', 'CWE78', 'none']
```text
[[35 42  0  0  2  1]
 [35 36  1  0  1  7]
 [39  8 17  1  6  9]
 [27  8 32  6  3  4]
 [ 8  6 12  1 51  2]
 [22  0  3  1  1 53]]
```

### Classification Report (Training):
```text
              precision    recall  f1-score   support

      CWE121       0.21      0.44      0.28        80
      CWE122       0.36      0.45      0.40        80
      CWE190       0.26      0.21      0.23        80
      CWE191       0.67      0.07      0.13        80
       CWE78       0.80      0.64      0.71        80
        none       0.70      0.66      0.68        80

    accuracy                           0.41       480
   macro avg       0.50      0.41      0.41       480
weighted avg       0.50      0.41      0.41       480
```

---